project:
  type: website
  output-dir: docs
  preview:
    port: 8080

website:
  title: "Aby's Portfolio"
  favicon: "misc/Xyba-Logo.ico"
  site-url: "https://abyoso-hapsoro.github.io/"
  repo-url: "https://github.com/abyoso-hapsoro/abyoso-hapsoro.github.io"
  repo-actions: [source]

  page-footer:
    right: "This page is built with 💚 using [Quarto](https://quarto.org/)."
    left: "&copy; Abyoso Hapsoro Nurhadi, 2024-2025"
  
  sidebar:
    pinned: true
    align: center
    tools:
    - icon: envelope
      href: mailto:abyoso.hapsoro@alumni.ui.ac.id
      text: "Mail"
    - icon: linkedin
      href: https://linkedin.com/in/abyoso-hapsoro/
      text: "LinkedIn"
    - icon: discord
      href: https://discord.com/users/xybafenix
      text: "Discord"
    - icon: github
      href: https://github.com/abyoso-hapsoro
      text: "GitHub"

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Homepage  # 🏠︎ Homepage
      - about.qmd
      - section: retrospective/retrospective.qmd
        contents:
          - retrospective/education.qmd
          - retrospective/experience.qmd
          - retrospective/training.qmd
          - retrospective/organization.qmd
          - retrospective/cv.qmd
          - retrospective/certifications.qmd
          - retrospective/achievements.qmd
      - section: projects/projects.qmd
        contents:
          - projects/mlaids.qmd
          - projects/mathematics.qmd
          - projects/others.qmd
      # - section: writings/writings.qmd
      #   contents:
      #     - writings/publications.qmd
      #     - writings/articles.qmd
      #     - writings/unpublished.qmd
      - misc.qmd
      - notes.qmd

# Set default YAML options
published-title: "Page Last Updated"
date-format: "D MMMM YYYY"
date: today
format:
  html:
    # includes:
    #   in-header:
    #     - scripts/redirect.js
    pre-render: scripts/deep-indexer.js
    highlight-style: solarized
    theme: minty
    css: styles.css
    link-external-newwindow: true
    code-copy: true
    code-overflow: wrap
    toc: true